spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myplus?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
#    baseline-version=0:

#mybatis配置
mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置别名
  type-aliases-package: work.mj.com.mj.pojo
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  autoDialect: true
  closeConn: true
#  hello: 你好
#  nihao: Hello
  offset-as-page-num: false