spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myplus?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  ##xml文件的路径配置
  mapper-locations:
    classpath: mapper/*.xml
  type-aliases-package: work.mj.com.mj.pojo
